"""A fixed list of facts for the student home view. Deterministic by date
rather than random -- the same fact holds all day regardless of how many
times the page reruns, and rotates without needing an external API or its
failure modes for something this low-stakes.

Sized to a full year (365+) rather than just a few dozen, so a school year
never repeats a fact on its way through -- see fact_of_the_day.
"""

from __future__ import annotations

from datetime import date

FACTS = [
    # --- animals -------------------------------------------------------------
    "Octopuses have three hearts, and two of them stop beating when it swims.",
    "A shrimp's heart is in its head.",
    "Butterflies taste with their feet.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "A group of flamingos is called a flamboyance.",
    "A group of crows is called a murder.",
    "Wombat poop is cube-shaped.",
    "Some turtles can breathe through their butts.",
    "An octopus can taste with its arms.",
    "Squirrels forget where they bury most of their nuts, planting forests by accident.",
    "Sharks existed before trees did.",
    "There's a species of jellyfish that can revert to a baby stage and is biologically immortal.",
    "A blue whale's heart is about the size of a small car.",
    "Elephants are one of the few animals that can recognize themselves in a mirror.",
    "A group of pandas is called an embarrassment.",
    "A snail can sleep for up to three years.",
    "Cows have best friends and get stressed when they're separated.",
    "Koalas have fingerprints so similar to humans that they've confused crime scenes.",
    "A group of owls is called a parliament.",
    "Starfish don't have brains or blood.",
    "Some frogs can freeze solid over winter and thaw back to life in spring.",
    "A crocodile can't stick its tongue out.",
    "Giraffes only need 5 to 30 minutes of sleep a day.",
    "A hummingbird's heart can beat up to 1,200 times a minute.",
    "Cows can walk upstairs but not downstairs, because of how their knees bend.",
    "A tiger's stripes are on its skin, not just its fur -- shave one and the pattern's still there.",
    "Dolphins have signature whistles that work like names for each other.",
    "Elephants can't jump.",
    "A cheetah can't roar; it chirps and purrs instead.",
    "Kangaroos can't walk backward.",
    "Some ants can carry 50 times their own body weight.",
    "Polar bear fur isn't white -- it's clear and hollow, and just scatters light to look white.",
    "A group of jellyfish is called a smack.",
    "Rats make a high-pitched laughing sound, too high for humans to hear, when they're tickled.",
    "An ostrich's eye is bigger than its brain.",
    "Sloths can hold their breath longer than dolphins can.",
    "Male seahorses are the ones who get pregnant and give birth.",
    "A group of rhinos is called a crash.",
    "Pigeons can recognize themselves in a mirror and remember hundreds of faces.",
    "Bees can recognize individual human faces.",
    "A snail has about 14,000 teeth.",
    "Woodpeckers have shock-absorbing skulls so they don't get concussions.",
    "A group of hedgehogs is called a prickle.",
    "Chickens are the closest living relatives of the T. rex.",
    "An octopus has nine brains -- one central one and one in each arm.",
    "Horses can sleep both lying down and standing up.",
    "A blue whale's tongue can weigh as much as an elephant.",
    "Flamingos are pink because of pigments in the shrimp and algae they eat.",
    "Otters use rocks as tools to crack open shellfish, and keep a favorite one in a skin pouch.",
    "Some spiders can catch the wind with silk and drift for miles -- it's called ballooning.",
    "A cat can't taste sweetness.",
    "Camels store fat in their humps, not water.",
    "Elephants can sense vibrations through their feet from miles away.",
    "A group of porcupines is called a prickle.",
    "Goats have rectangular pupils, which gives them a wider field of view.",
    "A group of lions is called a pride, but a group of tigers is called an ambush.",
    "Ravens can hold grudges against specific people for years.",
    "A pistol shrimp can snap its claw so fast it briefly boils the water around it.",
    "Slugs have four noses.",
    "An electric eel can produce a shock strong enough to stun a horse.",
    "A group of ferrets is called a business.",
    "Mantis shrimp can see colors humans can't even imagine.",
    "Dogs' noses have a unique print, just like human fingerprints.",
    "A tarantula can survive up to two years without eating.",
    "Cows produce more milk when they listen to calm music.",
    "A group of giraffes is called a tower.",
    "Penguins propose to their mates with a pebble.",
    "The tongue of a blue whale alone can weigh as much as a full-grown hippo.",
    "A group of kangaroos is called a mob.",
    "Some fish can change from one sex to the other during their lifetime.",
    "A hippo's sweat is naturally reddish and works as sunscreen.",
    "Certain species of ants can build living bridges out of their own bodies.",
    # --- space -----------------------------------------------------------------
    "A day on Venus is longer than a year on Venus.",
    "Venus is the only planet in our solar system that spins clockwise.",
    "It rains diamonds on Jupiter and Saturn.",
    "Astronauts say space smells like hot metal and burnt steak.",
    "A day on Mars is only about 40 minutes longer than a day on Earth.",
    "There are more stars in the universe than grains of sand on every beach on Earth.",
    "The Sun makes up about 99.8% of all the mass in the solar system.",
    "A teaspoon of a neutron star would weigh about a billion tons.",
    "About one million Earths could fit inside the Sun.",
    "Saturn is so light that it would float, if you had a bathtub big enough.",
    "The Moon has no wind or weather, so the Apollo astronauts' footprints are still there.",
    "A year on Mercury is just 88 Earth days.",
    "UY Scuti, one of the largest known stars, could hold Earth's entire orbit around the Sun inside it.",
    "Jupiter's Great Red Spot, a storm, has been raging continuously for at least 350 years.",
    "Light from the Sun takes about 8 minutes to reach Earth.",
    "Uranus rotates on its side, likely from a collision billions of years ago.",
    "The International Space Station circles Earth roughly every 90 minutes.",
    "Astronauts get slightly taller in space, since gravity isn't compressing their spine.",
    "A full NASA spacesuit costs more than $12 million.",
    "There's a planet, 55 Cancri e, that scientists think is partly made of diamond.",
    "The Milky Way is on a slow collision course with the Andromeda galaxy.",
    "Mercury and Venus are the only planets with no moons at all.",
    "A black hole isn't empty space -- it's matter packed unbelievably densely.",
    "Driving straight up at highway speed, you'd reach space in under an hour.",
    "There's a region of space called the Boötes Void that's almost completely empty for 330 million light-years across.",
    "Jupiter has at least 95 known moons.",
    "The Sun loses about 4 million tons of mass every second, turned into energy.",
    "The tallest volcano in the solar system, Olympus Mons on Mars, is nearly three times the height of Everest.",
    "Space is silent -- sound needs air or some other medium to travel through, and there isn't any.",
    "Halley's Comet won't be visible from Earth again until the year 2061.",
    "Saturn's rings are made almost entirely of ice.",
    "Every second, the Sun turns about 600 million tons of hydrogen into helium.",
    "A 'shooting star' isn't a star -- it's a speck of rock or dust burning up in the atmosphere.",
    "Neutron stars can spin over 600 times every second.",
    "Pluto hasn't even completed one full orbit of the Sun since it was discovered in 1930.",
    "Jupiter has the shortest day of any planet in the solar system, at about 10 hours.",
    "There are likely more planets in the universe than there are stars.",
    "Astronauts' tears don't fall in space -- they just pool up into a floating ball.",
    "A year on Neptune lasts about 165 Earth years.",
    "The Moon drifts about 1.5 inches farther from Earth every year.",
    "Metal touching identical metal in the vacuum of space can permanently fuse together -- it's called cold welding.",
    "Saturn is big enough to fit around 764 Earths inside it.",
    "A comet's tail always points away from the Sun, no matter which way the comet is moving.",
    "The footprints on the Moon are expected to last millions of years.",
    "Jupiter's Great Red Spot is a storm wider than Earth itself.",
    "There is more water locked in Earth's mantle than in all its oceans combined.",
    "The largest canyon in the solar system, Valles Marineris on Mars, is roughly as long as the continental United States is wide.",
    # --- science, physics & chemistry ------------------------------------------
    "A single bolt of lightning is hotter than the surface of the Sun.",
    "A bolt of lightning strikes Earth roughly 8 million times a day.",
    "Hot water can, under the right conditions, freeze faster than cold water.",
    "Some metals are so reactive that they explode on contact with water.",
    "Glass is technically a liquid that flows so slowly it looks solid.",
    "Diamonds can burn -- they're just pure carbon, like coal or wood.",
    "Bananas are naturally slightly radioactive because of the potassium in them.",
    "A single teaspoon of a black hole's matter would weigh more than a mountain.",
    "Sound travels about four times faster through water than through air.",
    "Helium makes your voice higher not by changing your vocal cords, but by changing how fast sound moves through it.",
    "There's a metal, gallium, that will melt in your hand at room temperature.",
    "Static electricity can spark at over 20,000 volts and barely be felt.",
    "The average cloud weighs over a million pounds.",
    "Water can exist as a solid, liquid, and gas at the exact same time, called its triple point.",
    "Rubber bands last longer when refrigerated, since heat and light break them down faster.",
    "The Eiffel Tower grows about 6 inches taller in summer heat, as the iron expands.",
    "A rainbow is actually a full circle -- from the ground, you just see the top half.",
    "Some jellyfish and plankton glow in the dark through a chemical reaction called bioluminescence.",
    "Lightning is about five times hotter than the surface of the Sun.",
    "Glass windows in very old buildings are sometimes thicker at the bottom, but not because glass actually flows over centuries -- that's a myth from old manufacturing methods.",
    "Antimatter is a real thing -- if it touches regular matter, both instantly convert to energy.",
    "A vacuum isn't truly empty -- particles can briefly pop in and out of existence there.",
    "Table salt is made from two dangerous substances -- sodium, which explodes in water, and chlorine, a toxic gas.",
    "Sound waves can be used to levitate small objects using a technique called acoustic levitation.",
    "The coldest temperature theoretically possible, absolute zero, has never actually been reached in a lab.",
    "Water expands by about 9% when it freezes, which is why ice floats.",
    "A single flash of lightning contains enough energy to toast about 100,000 slices of bread.",
    "Some liquids, like honey, are so thick that they can take years to visibly move, but they still count as liquids.",
    "The Northern Lights are caused by charged particles from the Sun colliding with Earth's atmosphere.",
    "Metal spoons feel colder than wooden ones at the same temperature because metal pulls heat from your hand faster.",
    "A rubber tire is actually a single, incredibly complex molecule.",
    "Quicksand isn't as dangerous as movies make it look -- humans float in it more than they sink.",
    "The loudest sound ever recorded, the 1883 Krakatoa eruption, was heard nearly 3,000 miles away.",
    "Freshly poured concrete can take decades to fully finish hardening.",
    "Glow sticks work by mixing two chemicals that react and release light instead of heat.",
    "Cracking your knuckles doesn't cause arthritis, despite the old warning -- it's just gas bubbles popping in the joint fluid.",
    "Wood floats because it's less dense than water, but ebony wood is dense enough to sink.",
    "A drop of water can bounce off a super-hydrophobic surface almost like a ball.",
    "The chemical that makes chili peppers spicy, capsaicin, doesn't actually burn your tongue -- it tricks the same nerves that detect real heat.",
    "There are more possible unique shuffles of a deck of cards than atoms on Earth.",
    "There are more possible chess games than atoms in the observable universe.",
    # --- history ----------------------------------------------------------------
    "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
    "The shortest war in recorded history lasted about 38 minutes.",
    "Honey never spoils -- archaeologists have found and eaten 3,000-year-old honey.",
    "The Great Wall of China is not actually visible from space with the naked eye.",
    "Oxford University is older than the Aztec Empire.",
    "Ancient Roman concrete has lasted 2,000 years and is, in some ways, tougher than modern concrete.",
    "The first Olympic Games, in 776 BC, only had one event: a footrace.",
    "Vikings likely never wore horned helmets -- that image came from 19th-century opera costumes.",
    "The guillotine was still legally used in France as late as 1977.",
    "Napoleon wasn't actually short -- he was around 5 foot 7, roughly average height for his era.",
    "Ancient Egyptians used to shave off their eyebrows to mourn their cats.",
    "The first known written complaint (a customer angry about bad copper) dates back nearly 3,800 years.",
    "The Great Fire of London in 1666 reportedly killed only a handful of recorded deaths.",
    "Ancient Romans used urine as an ingredient in laundry detergent and teeth whitening.",
    "The inventor of the Frisbee was, after he died, made into a Frisbee himself, as he'd requested.",
    "The first telephone call ever made was Alexander Graham Bell asking his assistant for help.",
    "The Titanic's chief baker survived the sinking by drinking enough alcohol to stay warm in the freezing water for hours.",
    "Ancient Sparta left weak or sickly newborns exposed on a hillside, a practice most historians now doubt happened as commonly as the legend claims.",
    "During the California Gold Rush, some prospectors made more money selling jeans and shovels than gold.",
    "The Eiffel Tower was originally meant to be a temporary structure, taken down after 20 years.",
    "The first vending machines, in ancient Greece, dispensed holy water for a coin.",
    "Isaac Newton invented the cat door.",
    "Chewing gum has been around in some form for thousands of years -- ancient people chewed tree resin.",
    "Medieval knights sometimes needed a small crane to get onto their horse in full armor -- another myth, since well-fitted armor was actually light enough to move freely in.",
    "The shortest reigning monarch in history ruled for only about 20 minutes.",
    "The first American Thanksgiving meal likely didn't include mashed potatoes or pumpkin pie.",
    "Paul Revere's midnight ride was actually a group effort with other riders, not a solo trip.",
    "Ancient Chinese doctors used to diagnose illnesses partly by listening to a patient's pulse for up to an hour.",
    "The Statue of Liberty was originally a copper color, not green -- it turned green over decades from oxidation.",
    "Ancient Babylonians used a base-60 number system, which is why we have 60 minutes in an hour today.",
    "The first color photograph was taken in 1861.",
    "The Wright brothers' first flight, in 1903, covered a shorter distance than the wingspan of a modern Boeing 747.",
    "Silly Putty was invented by accident while scientists were trying to create synthetic rubber during World War II.",
    "The first computer bug was an actual moth stuck in a relay in 1947.",
    "Ancient Roman gladiators were mostly vegetarian, likely to build a layer of fat that protected against cuts.",
    "The Pony Express only operated for about 18 months before the telegraph made it obsolete.",
    "Ancient Egyptians played one of the earliest known board games, senet, over 5,000 years ago.",
    "During World War II, the Slinky was invented by accident when a spring fell off a shelf and 'walked.'",
    "The world's oldest known recipe, dating back nearly 4,000 years, is for beer.",
    "Some medieval European towns put animals, like pigs, on trial in real courts for crimes.",
    # --- geography & nature ------------------------------------------------------
    "Antarctica is technically the largest desert in the world.",
    "Mount Everest grows about 4 millimeters taller every year.",
    "Russia spans 11 time zones -- more than any other country.",
    "There's a lake in Bolivia, Salar de Uyuni, so flat and reflective it looks like a mirror stretching to the horizon.",
    "Africa contains parts of all five hemispheres.",
    "The Amazon Rainforest produces roughly 20% of the world's oxygen.",
    "The Sahara Desert was green and covered in lakes and vegetation only a few thousand years ago.",
    "Canada has more lakes than the rest of the world's countries combined.",
    "The Dead Sea is so salty that swimmers float without even trying.",
    "There's an underwater waterfall illusion off Mauritius caused by sand and silt sliding down an oceanic shelf.",
    "The Pacific Ocean is wider than the Moon.",
    "A single flash of lightning can be over 5 miles long.",
    "The world's longest mountain range, the Mid-Atlantic Ridge, is underwater, running through the middle of the Atlantic Ocean.",
    "There's a town in Norway, Rjukan, that had to build giant mirrors to reflect sunlight into its valley in winter.",
    "The world's smallest country, Vatican City, is smaller than most golf courses.",
    "Iceland has no mosquitoes, thanks to its unique climate and glacial cycles.",
    "There's a river in Colombia, the Caño Cristales, that turns bright red, yellow, and blue from plant life.",
    "The Sahara Desert is roughly the size of the entire United States.",
    "Mount Everest's summit is technically closer to space than most mountains, because Earth bulges at the equator.",
    "Australia is wider than the Moon.",
    "A single iceberg can weigh more than 100 million tons.",
    "The world's largest hot desert isn't the Sahara -- it's Antarctica, if you count deserts by lack of rainfall.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Death Valley, one of the hottest places on Earth, also gets snow some winters.",
    "The Amazon River has no bridges crossing it along its entire length.",
    "The world's oceans hold about 97% of all of Earth's water.",
    "There's a glacier cave in Iceland where the ice glows an intense electric blue.",
    "New Zealand was one of the last major landmasses on Earth to be settled by humans.",
    "The Grand Canyon is so big it has its own weather patterns.",
    "Yellowstone National Park sits on top of a supervolcano.",
    "Volcanoes can produce their own lightning, caused by ash particles rubbing together.",
    "A group of islands, the Maldives, is the flattest country on Earth, barely above sea level.",
    "The world's tallest tree, a redwood named Hyperion, is taller than a 35-story building.",
    "Lake Baikal in Russia holds about 20% of all the fresh, unfrozen water on Earth's surface.",
    "There's a beach in the Maldives that glows blue at night from bioluminescent plankton.",
    # --- human body ---------------------------------------------------------------
    "Your stomach gets an entirely new lining every few days so it doesn't digest itself.",
    "Humans share about 60% of their DNA with a banana.",
    "Your nose can distinguish over a trillion different scents.",
    "Bones are about five times stronger than steel of the same weight.",
    "The human brain uses about 20% of the body's total energy, despite being only 2% of its weight.",
    "You're about 1 centimeter taller in the morning than at night, since gravity compresses your spine during the day.",
    "It's impossible to tickle yourself, because your brain predicts and cancels out your own touch.",
    "Your body produces enough heat in 30 minutes to boil half a gallon of water.",
    "Fingernails grow faster than toenails.",
    "The human heart beats about 100,000 times a day.",
    "Human blood vessels laid end to end could circle the Earth more than twice.",
    "Babies are born with about 300 bones, but adults only have 206, since some fuse together over time.",
    "Your ears never stop growing, even as an adult.",
    "It takes about 17 muscles to smile and around 43 to frown.",
    "A sneeze can travel out of your mouth at over 100 miles per hour.",
    "Your eyes stay the same size from birth, but your nose and ears never stop growing.",
    "Humans lose about 50 to 100 strands of hair every day, and it's completely normal.",
    "Taste buds are replaced roughly every two weeks.",
    "The acid in your stomach is strong enough to dissolve metal over time.",
    "Left-handed people make up only about 10% of the population.",
    "Your skin is your body's largest organ.",
    "A human sneeze can spread germs several feet in every direction.",
    "You blink around 15 to 20 times every minute, without even thinking about it.",
    "The human body contains enough carbon to fill about 9,000 pencils.",
    "Your smallest bone, the stapes, is inside your ear and is about the size of a grain of rice.",
    "It's possible to hiccup for years at a time -- the longest recorded case lasted 68 years.",
    "The human brain can generate more electrical impulses in a day than all the world's phones combined.",
    "You produce about a liter of saliva every day.",
    "Goosebumps are a leftover reflex from ancestors who had more body hair to trap warmth.",
    "The human body has enough iron in it to make a small nail.",
    # --- inventions & technology ------------------------------------------------
    "The first video game, created in 1958, was a simple tennis simulation shown on an oscilloscope.",
    "The first text message ever sent, in 1992, simply said 'Merry Christmas.'",
    "The inventor of the microwave discovered its heating effect after a candy bar melted in his pocket.",
    "Bubble wrap was originally invented to be a textured wallpaper.",
    "QWERTY keyboards were designed to slow typists down and prevent old typewriters from jamming.",
    "The first computer mouse, from the 1960s, was carved out of wood.",
    "Velcro was invented after its creator noticed how burrs stuck to his dog's fur.",
    "The first webcam was built just so scientists could check if a coffee pot was full without leaving their desks.",
    "The @ symbol in email addresses was chosen in 1971 mostly because it was rarely used elsewhere in text.",
    "The World Wide Web was made freely available to everyone, with no royalties, by its inventor.",
    "The first alarm clock could only ring at one set time: 4 a.m.",
    "The first product ever scanned with a barcode was a pack of chewing gum, in 1974.",
    "Play-Doh was originally invented and sold as a wallpaper cleaner.",
    "The first item ever sold on eBay was a broken laser pointer.",
    "The inventor of the Snickers bar named it after his family's favorite horse.",
    "The first camera phone was invented in 1999 in Japan.",
    "Post-it Notes were invented by accident, after a scientist created a glue that was too weak to be useful for anything else.",
    "The first computer virus was created in 1983 as a college research project.",
    "The zipper was originally called a 'clasp locker' when it was first patented.",
    "The traffic light was invented before the modern automobile existed in large numbers.",
    "LEGO bricks from 1958 still connect perfectly with LEGO bricks made today.",
    "Roller coasters were originally inspired by ice-covered wooden slides in 17th-century Russia.",
    "The first webpage ever created is still online today.",
    "Coca-Cola was originally green, before dye changed it to the color people know now.",
    "The paperclip has barely changed in design since it was patented in 1899.",
    "The Super Soaker was invented by a NASA engineer working on a different cooling project entirely.",
    "The first computer programmer was a woman, Ada Lovelace, in the 1840s -- before electronic computers even existed.",
    "The candy Pez was originally marketed as a breath mint for adults, not a kids' candy.",
    "Bubble gum was accidentally invented while trying to make a better rubber substitute.",
    "The inventor of the ballpoint pen also designed the first push-button retractable mechanism used today.",
    # --- language & words -----------------------------------------------------
    "The dot over a lowercase i or j has a name: a tittle.",
    "'Set' has more definitions in the dictionary than any other English word.",
    "The longest word in a major English dictionary describes a lung disease and has 45 letters.",
    "English has no official governing body, unlike French or Spanish, which have language academies.",
    "The word 'Mississippi' can be typed using only the left hand on a standard keyboard.",
    "A pangram is a sentence using every letter of the alphabet at least once, like 'the quick brown fox jumps over the lazy dog.'",
    "The shortest complete sentence in English is 'Go.'",
    "'Bookkeeper' and 'bookkeeping' are the only common English words with three consecutive double letters.",
    "The word 'nerd' first appeared in a Dr. Seuss book in 1950.",
    "'OK' is one of the most widely understood words in the entire world, across almost every language.",
    "The word 'set' can act as a noun, verb, and adjective, and has hundreds of distinct meanings.",
    "There's no official word in English for the smell of rain, though many languages have one -- 'petrichor' describes it in scientific terms.",
    "Alphabetically, 'goldfish' is the longest common English word with its letters in order.",
    "The word 'alphabet' comes from the first two letters of the Greek alphabet: alpha and beta.",
    "'Almost' is the longest common English word with all its letters in alphabetical order.",
    "The word 'robot' comes from a Czech word meaning forced labor, first used in a 1920 play.",
    "'Q' is the only letter in the English alphabet that doesn't appear in the name of any U.S. state.",
    "Shakespeare is credited with inventing or popularizing over 1,700 English words.",
    "The word 'sarcasm' comes from a Greek word that literally means 'to tear flesh.'",
    "A word for a word that sounds like what it describes, like 'buzz' or 'sizzle,' is called onomatopoeia.",
    "The longest place name in the world, in New Zealand, has 85 letters.",
    "The dot on top of a lowercase letter isn't decorative -- it helps readers tell letters apart at a glance.",
    "'Strengths' is the longest common English word with only one vowel.",
    "The symbol '&' is called an ampersand, and it comes from a stylized way of writing 'et,' Latin for 'and.'",
    "English borrowed the word 'robot,' 'ketchup,' and 'shampoo' from three completely different languages.",
    # --- math & numbers -----------------------------------------------------
    "There are more possible arrangements of a Rubik's Cube than atoms on Earth.",
    "Zero wasn't formally used as a number in most of the ancient world until centuries after counting began.",
    "A 'googol' is the number 1 followed by 100 zeros -- and it's where the company Google got its name, with a spelling change.",
    "Pi has been calculated to over 100 trillion digits, and it never repeats or ends.",
    "The number 40 is the only number in English spelled with letters in alphabetical order.",
    "If you fold a piece of paper in half 42 times, in theory it would be thick enough to reach the Moon.",
    "A 'leap second' is occasionally added to clocks worldwide to keep them in sync with Earth's slightly uneven rotation.",
    "There are exactly as many rational numbers as whole numbers, even though it seems like there should be more.",
    "A standard deck of 52 playing cards can be shuffled into more unique orders than there are atoms on Earth.",
    "The number 9 has a strange multiplication trick: any number multiplied by 9 has digits that add up to 9.",
    "A palindrome number reads the same forward and backward, like 12321.",
    "The Fibonacci sequence -- where each number is the sum of the two before it -- shows up in sunflower seed patterns and pinecones.",
    "In binary, computers represent every number, letter, and image using only 0s and 1s.",
    "A 'light-year' measures distance, not time -- it's how far light travels in one year.",
    "There is no largest prime number -- mathematicians have proven the list goes on forever.",
    "The equals sign (=) was invented in 1557 because the mathematician was tired of writing 'is equal to' over and over.",
    "A hexagon is the most efficient shape for tiling a surface with the least material, which is why bees use it for honeycomb.",
    "Chess has more possible games than there are seconds since the universe began.",
    "The number zero was independently invented by ancient civilizations in India, the Maya Empire, and Babylon.",
    "A million seconds is about 11.5 days, but a billion seconds is about 31.7 years.",
    # --- food & plants -----------------------------------------------------
    "Bananas are berries, but strawberries technically aren't.",
    "Carrots were originally purple before farmers bred orange varieties.",
    "Apples float in water because they're about 25% air.",
    "Peanuts aren't actually nuts -- they're legumes, related to beans and peas.",
    "Honey is the only food that never spoils if stored properly.",
    "Chocolate was once used as currency by the ancient Maya and Aztec civilizations.",
    "A pineapple takes almost two years to grow to full size.",
    "Cashews grow hanging off the bottom of a fruit called a cashew apple.",
    "The world's hottest pepper is rated at over 2 million Scoville units, hundreds of times hotter than a jalapeño.",
    "Rice is the staple food for more than half of the world's population.",
    "Watermelon is about 92% water.",
    "Almonds are technically seeds, not true nuts.",
    "Ketchup was sold as medicine in the 1830s, in pill form, claiming to cure indigestion.",
    "The world's largest fruit, jackfruit, can weigh over 100 pounds.",
    "Sunflowers can track the Sun's movement across the sky when they're young, a behavior called heliotropism.",
    "A single vanilla bean can take up to nine months to fully develop.",
    "Broccoli, cauliflower, cabbage, and kale are all the same plant species, bred into different shapes.",
    "The most expensive spice in the world, saffron, comes from hand-picked crocus flowers.",
    "Some bamboo species can grow nearly 3 feet in a single day.",
    "Popcorn has been found in ancient burial sites in Peru dating back thousands of years.",
    # --- weird records & miscellaneous ---------------------------------------
    "The Mona Lisa has no eyebrows -- eyebrow plucking was fashionable when it was painted.",
    "The unicorn is the official national animal of Scotland.",
    "The longest recorded flight of a chicken lasted about 13 seconds.",
    "The world's largest snowflake on record was reportedly 15 inches wide.",
    "A single cloud can contain millions of pounds of water and still float.",
    "The world's tallest LEGO tower ever built was taller than a 25-story building.",
    "The record for the longest domino chain toppled is over 4.8 million dominoes.",
    "A hiccuping fit can, in rare recorded cases, last for years at a time.",
    "The most valuable Pokémon card ever sold went for well over $5 million.",
    "The record for the largest pizza ever made was bigger than a football field.",
]


def fact_of_the_day(today: date | None = None) -> str:
    """The same fact all day, every day -- deterministic on the date, not
    random, so it doesn't change if the page reruns twice in a minute. The
    list is sized to a full year so a school year's worth of days never
    wraps around and repeats."""
    today = today or date.today()
    return FACTS[today.toordinal() % len(FACTS)]
